version: "3.9"
services:
  dev-postgres:
    image: postgres:18.1-alpine
    ports:
      - 5422:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: echo_lesson_db
    restart: always
    networks:
      - lesson
networks:
  lesson:
